######################################################################
# Automatically generated by qmake (3.0) ? 10? 16 23:52:33 2013
######################################################################

TEMPLATE = app
TARGET = sample
INCLUDEPATH += . src

# Input
HEADERS += src/main_window.hpp
SOURCES += src/main.cpp src/main_window.cpp
RESOURCES += src/tux.qrc

QT += widgets
